[phases.setup]
nixPkgs = [
    "php84",
    "php84Extensions.pdo_mysql",
    "php84Extensions.intl",
    "php84Extensions.zip",
    "php84Extensions.bcmath",
    "php84Extensions.gd",
    "php84Extensions.opcache",
    "php84Extensions.redis",
    "php84Extensions.mbstring",
    "php84Extensions.dom",
    "php84Extensions.xml",
    "php84Extensions.curl",
    "composer",
    "nodejs_22"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --optimize-autoloader --no-dev --no-interaction --no-scripts"
]

[start]
cmd = "sh -c 'chmod -R 777 storage bootstrap/cache && php artisan storage:link && php artisan config:clear && php artisan cache:clear && php -S 0.0.0.0:${PORT:-8080} -t public router.php'"
