[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo_mysql", "php82Extensions.zip", "php82Extensions.bcmath", "nginx"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan optimize:clear",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
